### test 1
GET http://localhost:8090/send?topic=test-topic&key=key-1&message=hihi

### test 2
GET http://localhost:8090/send?topic=topic1&key=key-1&message=hihi

### test 3
GET http://localhost:8090/send?topic=topic2&key=key-1&message=hihi

### test 4
GET http://localhost:8090/send?topic=topic3&key=key-1&message=hihi

### test 5
GET http://localhost:8090/send?topic=topic4&key=key-1&message=hihi
